from setuptools import setup, find_packages

setup(
    name='STMiner',
    version='1.0.0',
    author='PSSUN',
    url='https://github.com/PSSUN/STMiner',
    license='MIT License',
    description='Python package for spatial transcriptomics data analysis',
    author_email='sunpeisen@stu.xjtu.edu.cn',
    packages=find_packages(),
    platforms=['Linux', 'Mac', 'Windows'],
    keywords=['STMiner',
              'gaussian mixture models',
              'GMM',
              'hellinger distance',
              'Spatial transcriptomics'],
    install_requires=['anndata>=0.9.2',
                      'bioservices>=1.11.2',
                      'matplotlib>=3.7.1',
                      'networkx>=3.1',
                      'numba>=0.57.0',
                      'numpy>=1.24.3',
                      'pandas>=2.0.3',
                      'Pillow>=9.4.0',
                      'plotly>=5.16.1',
                      'scanpy>=1.9.5',
                      'scikit_learn>=1.3.0',
                      'scipy>=1.11.1',
                      'seaborn>=0.12.2',
                      'setuptools>=68.0.0',
                      'tifffile>=2021.4.8',
                      'tqdm']
)
